src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cette adresse existe déjà !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @var string|null */
    public $captcha;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     *
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Company;

    /**
     * @ORM\ManyToOne(targetEntity=EventReviews::class, inversedBy="user")
     */
    private $eventReviews;

    /**
     * @ORM\OneToMany(targetEntity=Events::class, mappedBy="user")
     */
    private $events;

    public function __construct()
    {
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->Company;
    }

    public function setCompany(string $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    public function getEventReviews(): ?EventReviews
    {
        return $this->eventReviews;
    }

    public function setEventReviews(?EventReviews $eventReviews): self
    {
        $this->eventReviews = $eventReviews;

        return $this;
    }

    /**
     * @return Collection|Events[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Events $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setUser($this);
        }

        return $this;
    }

    public function removeEvent(Events $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getUser() === $this) {
                $event->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Events;
use App\Entity\SearchEvent;
use App\Form\EventsType;
use App\Form\EditUserType;
use App\Entity\SocialLinks;
use App\Form\EditUserBusinessType;
use App\Form\SearchEventType;
use App\Repository\EventsRepository;
use App\Repository\SocialLinksRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/")
 */
class HomeController extends AbstractController
{
    /**
     * @Route("", name="home")
     */
    public function index(EventsRepository $eventsRepository)
    {
        return $this->render('home/index.html.twig', ['lastEvent' => $eventsRepository->findOneBy([], ['id' => 'DESC'])]);
    }

    /**
     * @Route("/mes-evenements/nouveau", name="events_business_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $event = new Events();
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $event->setSlug($event->slugify($event->getName()));
            $event->setUser($this->getUser());

            if (!is_null($form->get('fbUrl')->getData())) {
                $ss = new SocialLinks();
                $ss->setUrl($form->get('fbUrl')->getData())
                    ->setEvent($event)
                    ->setType('facebook')
                    ->setClass('fa-facebook-f');
                $entityManager->persist($ss);
            }
            if (!is_null($form->get('twUrl')->getData())) {
                $ss = new SocialLinks();
                $ss->setUrl($form->get('twUrl')->getData())
                    ->setEvent($event)
                    ->setType('twitter')
                    ->setClass('fa-twitter');
                $entityManager->persist($ss);
            }

            $banner = $event->getBanner();
            $logo = $event->getLogo();

            if ($banner) {
                $originalBannername = pathinfo($banner->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeBannername = $event->slugify($originalBannername);
                $newBannername = $safeBannername.'-'.uniqid().'.'.$banner->guessExtension();

                $banner->move(
                    $this->getParameter('banners'),
                    $newBannername
                );
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $event->setBanner($newBannername);
            }

            if ($logo) {
                $originallogoname = pathinfo($logo->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safelogoname = $event->slugify($originallogoname);
                $newlogoname = $safelogoname.'-'.uniqid().'.'.$logo->guessExtension();

                $logo->move(
                    $this->getParameter('logos'),
                    $newlogoname
                );
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $event->setLogo($newlogoname);
            }
            

            $event->setOrganizer($this->getUser()->getFirstName().' '.$this->getUser()->getLastName());
            $entityManager->persist($event);
            $entityManager->flush();
            return $this->redirectToRoute('my_events');
        }

        return $this->render('business/addEvent.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("mes-evenements", name="my_events", methods={"GET"})
     */
    public function myEvents(EventsRepository $eventsRepository, PaginatorInterface $paginator, Request $request)
    {
        $searchEvent = new SearchEvent();
        $form = $this->createForm(SearchEventType::class, $searchEvent);
        $form->handleRequest($request);
        $pagination = $paginator->paginate(
            $eventsRepository->findByAllQueriesByUser($searchEvent, $this->getUser()), /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            5 /*limit per page*/
        );
        return $this->render('home/myEvents.html.twig', [
            'events' => $pagination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("mes-evenements/{slug}", name="my_events_business" , methods={"GET"})
     */
    public function myEventsBusiness(Events $event, Request $request)
    {
        return $this->render('home/event-single-business.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * @Route("mes-evenements/modification/{slug}", name="my_events_business_edit", methods={"GET","POST"})
     */
    public function myEventsBusinessEdit(Events $event, Request $request, SocialLinksRepository $socialLinksRepository)
    {
        $oldBanner = $event->getBanner();
        $oldLogo = $event->getLogo();

        $currentEventName = $event->getName();
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            if (count($event->getSocialLinks()) == 0) {
                if (!is_null($form->get('fbUrl')->getData())) {
                    $newLink = new SocialLinks();
                    $newLink->setType('facebook')
                        ->setClass('fa-facebook-f')
                        ->setUrl($form->get('fbUrl')->getData());
                    $this->getDoctrine()->getManager()->persist($newLink);
                    $event->addSocialLink($newLink);
                }

                if (!is_null($form->get('twUrl')->getData())) {
                    $newLink = new SocialLinks();
                    $newLink->setType('twitter')
                        ->setClass('fa-twitter')
                        ->setUrl($form->get('twUrl')->getData());
                    $this->getDoctrine()->getManager()->persist($newLink);
                    $event->addSocialLink($newLink);
                }
            } else if (count($event->getSocialLinks()) == 1) {
                foreach ($event->getSocialLinks() as $link) {
                    if ($link->getType() == 'facebook' && !is_null($form->get('twUrl')->getData())) {
                        $newLink = new SocialLinks();
                        $newLink->setType('twitter')
                            ->setClass('fa-twitter')
                            ->setUrl($form->get('twUrl')->getData());
                        $this->getDoctrine()->getManager()->persist($newLink);
                        $event->addSocialLink($newLink);
                    } else if ($link->getType() == 'twitter' && !is_null($form->get('fbUrl')->getData())) {
                        $newLink = new SocialLinks();
                        $newLink->setType('facebook')
                            ->setClass('fa-facebook-f')
                            ->setUrl($form->get('fbUrl')->getData());
                        $this->getDoctrine()->getManager()->persist($newLink);
                        $event->addSocialLink($newLink);
                    }
                }
            } else {
                foreach ($event->getSocialLinks() as $link) {

                    if ($link->getType() == 'facebook') {
                        if (!is_null($form->get('fbUrl')->getData()) && $link->getUrl() != $form->get('fbUrl')->getData()) {
                            $link->setUrl($form->get('fbUrl')->getData());
                        }
                    } else if ($link->getType() == 'twitter') {
                        if (!is_null($form->get('twUrl')->getData()) && $link->getUrl() != $form->get('twUrl')->getData()) {
                            $link->setUrl($form->get('twUrl')->getData());
                        }
                    }
                }
            }
            if ($event->getName() != $currentEventName) {
                
                $event->setSlug($event->slugify($event->getName()));
            }

            $banner = $event->getBanner();
            $logo = $event->getLogo();

            if ($banner && $banner != $oldBanner) {
                $originalBannername = pathinfo($banner->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeBannername = $event->slugify($originalBannername);
                $newBannername = $safeBannername.'-'.uniqid().'.'.$banner->guessExtension();

                $banner->move(
                    $this->getParameter('banners'),
                    $newBannername
                );
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $event->setBanner($newBannername);
            }else{
                $event->setBanner($oldBanner);
            }

            if ($logo && $banner != $oldLogo) {
                $originallogoname = pathinfo($logo->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safelogoname = $event->slugify($originallogoname);
                $newlogoname = $safelogoname.'-'.uniqid().'.'.$logo->guessExtension();

                $logo->move(

templates/home/editProfile.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<section>
		<div class="container mb-5">
			<h1 class="text-center">Mon compte</h1>
			<h4 class="text-center">Modification</h4>
			<div class="row mt-5">
				<div class="col-md-12">
					{{ form_start(form, {'attr':{'class':'row'}}) }}
					<div class="col-md-12">
						<div class="form-group">
							{{ form_label(form.email) }}
							{{ form_widget(form.email) }}
						</div>
					</div>
					{% if is_granted('ROLE_BUSINESS') %}
						<div class="col-md-4">
							<div class="form-group">
								{{ form_label(form.firstName) }}
								{{ form_widget(form.firstName) }}
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group">
								{{ form_label(form.lastName) }}
								{{ form_widget(form.lastName) }}
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group">
								{{ form_label(form.company) }}
								{{ form_widget(form.company) }}
							</div>
						</div>
					{% else %}
						<div class="col-md-6">
							<div class="form-group">
								{{ form_label(form.firstName) }}
								{{ form_widget(form.firstName) }}
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								{{ form_label(form.lastName) }}
								{{ form_widget(form.lastName) }}
							</div>
						</div>
					{% endif %}

					<div class="col-md-12">
						<h4 class="text-center">Mot de passe</h4>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							{{form_label(form.oldPassword)}}
							{{form_widget(form.oldPassword)}}
							{% for errorPassword in app.flashes('passwordError') %}
								<div id="errorPassword" data-error="{{ errorPassword }}"></div>
								<script>
									Toastify({
text: document.querySelector('#errorPassword').dataset.error,
duration: 10000,
close: true,
gravity: "bottom",
position: "left",
backgroundColor: "linear-gradient(to right, #CB356B, #BD3F32)",
stopOnFocus: true
}).showToast();
								</script>
							{% endfor %}
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							{{form_label(form.newPassword)}}
							{{form_widget(form.newPassword)}}
							{% for newPasswordError in app.flashes('newPasswordError') %}

								<div id="errorPassword" data-error="{{ newPasswordError }}"></div>
								<script>
									Toastify({
text: document.querySelector('#errorPassword').dataset.error,
duration: 3000,
close: true,
gravity: "bottom",
position: "left",
backgroundColor: "linear-gradient(to right, #CB356B, #BD3F32)",
stopOnFocus: true
}).showToast();
								</script>
							{% endfor %}
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group text-center">
							<button type="submit" class="btn btn-success">Modifier</button>
							<a href="{{ path('profile') }}">
								<button type="button" class="btn btn-info">Retour à mon profil</button>
							</a>
						</div>
					</div>
					{{ form_end(form) }}
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/home/event-single-business.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	{% if event.banner %}
	<section class="hero-banner p-2" style="background:url('{{ asset('uploads/banners/'~ event.banner) }}')">
	{% else %}
		<section class="hero-banner p-2 bg-dark">
	{% endif %}
		<div class="container text-center">
			<span class="hero-banner-icon">
				{% if event.logo %}
				<img src="{{ asset('uploads/logos/'~ event.logo) }}" width="100" alt="Logo evenement">
				{% else %}
					<i class="fa fa-gamepad"></i>
				{% endif %}
			</span>
			<p>{{ event.launchDate|format_datetime(pattern='d MMMM yyyy') }}
				-
				{{ event.stopDate|format_datetime(pattern='d MMMM yyyy') }},
				{{ event.city }}</p>
			<h1>{{ event.name }}</h1>

		</div>
	</section>
	<section class="container pt-5 pb-5">
		<div class="text-center">
			<a href="{{ path('profile') }}">
				<button class="button button-header">Mon compte</button>
			</a>
			<a href="{{ path('my_events') }}">
				<button class="button button-header">Mes evènements</button>
			</a>
			<a href="{{ path('my_events_business_edit', {'slug':event.slug}) }}">
				<button class="button button-header">Modifier mon évènement</button>
			</a>
		</div>
		<div class="row mt-5">
			<div class="col-md-6 text-center text-md-left">

				<h2>Description</h2>
				<p>{{ event.shortDesc }}</p>
			</div>
			<div class="col-md-6 justify-content-center">
				{% if date().diff(event.launchDate).invert == 1 and date().diff(event.stopDate).invert == 0 %}
                    <h2 class="text-center">Evènement en cours <i class="fa fa-check text-success"></i></h2>
                    {# Si la date du jour est supérieure que la date de lancement de l'évènement et si la date du jour est supérieure à la date de fin #}
                {% elseif date().diff(event.launchDate).invert == 1 and date().diff(event.stopDate).invert == 1 %}
                    <h2 class="text-center">Evènement terminé <i class="fa fa-check text-success"></i></h2>
                    {% else %}
                    <ul class="clockdiv text-center" id="clockdiv">
							<li class="clockdiv-single clockdiv-day">
								<h1 class="days"></h1>
								<span class="smalltext">Jours</span>
							</li>
							<li class="clockdiv-single clockdiv-hour">
								<h1 class="hours"></h1>
								<span class="smalltext">Heures</span>
							</li>
							<li class="clockdiv-single clockdiv-minute">
								<h1 class="minutes"></h1>
								<span class="smalltext">Minutes</span>
							</li>
						</ul>
						<div class="clockdiv-content text-center">
							<p class="h4 primary-text2 mb-2" id="launchDate" data-date="{{ event.launchDate|date('Y-m-d h:i:s') }}"></p>
							
						</div>
                {% endif %}

				<div class="clockdiv-content text-center">
					<p class="h4 primary-text2 mb-2">{{ event.launchDate|format_datetime(pattern='d MMMM yyyy') }}
						-
						{{ event.stopDate|format_datetime(pattern='d MMMM yyyy') }}</p>
				</div>
			</div>
		</div>
		<div class="row mt-5">
			<div class="col-md-4 mb-3 text-center text-md-left general-infos">
				<h2>Informations générales</h2>
				<span class="mt-3" id="launchDate" data-date="{{ event.launchDate|date('Y-m-d h:i:s') }}">Date de début:
					{{ event.launchDate|format_datetime(pattern='d MMMM yyyy') }}
					à
					{{ event.launchDate|date('H:i') }}</span>
				<hr>
				<span>Date de fin:
					{{ event.stopDate|format_datetime(pattern='d MMMM yyyy') }}
					à
					{{ event.stopDate|date('H:i') }}</span>
				<hr>
				<span>Capacités:
					{% if event.ticketNumber == 0  %}Places illimitées
					{% else %}
						{{ event.ticketNumber }}
						place(s) disponible(s)
					{% endif %}
				</span>
				<hr>
				<span>Organisateur:
					{{ event.user.company ? event.user.company  :event.user.firstName +' '+event.user.lastName  }}</span>
				<hr>
				<span>Adresse: {{ event.address }}, {{ event.city }}, {{ event.department ? event.department.departmentName : "" }}, {{ event.cp }}</span>
				{# <button class="button button-header mt-5">Être alerté</button> #}
				<hr>
				
				
				<h5>Jeux disponibles</h5>
				<ul>
					{% for game in event.availableGames %}
						<li>{{ game.gameName }}</li>
					{% endfor %}
				</ul>
				<hr>
				<h5>Support(s)</h5>
				<ul>
					{% for support in event.support %}
						<li>{{ support.platformName }}</li>
					{% endfor %}
				</ul>
				<hr>
				<div class="d-flex flex-row justify-content-center">
					{% for socialLink in event.socialLinks %}
						{% if socialLink.type == 'facebook' %}
							<a href="{{ socialLink.url }}" target="_blank">
								<button class="button button-header">
									<i class="fab fa-facebook-f"></i>
								</button>
							</a>
						{% elseif socialLink.type == 'twitter' %}
							<a href="{{ socialLink.url }}" target="_blank">
								<button class="button button-header ml-1">
									<i class="fab fa-twitter"></i>
								</button>
							</a>
						{% endif %}
					{% endfor %}
				</div>
			</div>
			<div class="col-md-8 text-center text-md-left">
				<p>{{ event.longDesc }}</p>
			</div>
		</div>
	</section>
{% endblock %}

{% block javascripts %}
	<script>
		function getTimeRemaining(endtime) {
var t = Date.parse(new Date(endtime)) - Date.parse(new Date());
// var seconds = Math.floor((t / 1000) % 60);
var minutes = Math.floor((t / 1000 / 60) % 60);
var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
var days = Math.floor(t / (1000 * 3600 * 24));
return {
'total': t, 'days': days, 'hours': hours, 'minutes': minutes
// 'seconds': seconds
};
}

function initializeClock(id, endtime) {
var clock = document.getElementById(id);
var daysSpan = clock.querySelector('.days');
var hoursSpan = clock.querySelector('.hours');
var minutesSpan = clock.querySelector('.minutes');
// var secondsSpan = clock.querySelector('.seconds');

function updateClock() {
var t = getTimeRemaining(document.getElementById('launchDate').dataset.date);

daysSpan.innerHTML = t.days;
hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
// secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);

if (t.total <= 0) {
clearInterval(timeinterval);
}
}

updateClock();
var timeinterval = setInterval(updateClock, 1000);
}

var deadline = new Date(Date.parse(new Date(document.getElementById('launchDate').dataset.date)) + 30 * 24 * 60 * 60 * 1000);
initializeClock('clockdiv', deadline);
	</script>
{% endblock %}

templates/home/profile.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<section>
		{% for success in app.flashes('successWithPw') %}
			<div id="success" data-error="{{ success }}"></div>
			<script>
				Toastify({
text: document.querySelector('#success').dataset.error,
duration: 10000,
close: true,
gravity: "bottom",
position: "left",
backgroundColor: "linear-gradient(to right, #11998e, #38ef7d)",
stopOnFocus: true
}).showToast();
			</script>
		{% endfor %}
		{% for success in app.flashes('success') %}
			<div id="success" data-error="{{ success }}"></div>
			<script>
				Toastify({
text: document.querySelector('#success').dataset.error,
duration: 10000,
close: true,
gravity: "bottom",
position: "left",
backgroundColor: "linear-gradient(to right, #11998e, #38ef7d)",
stopOnFocus: true
}).showToast();
			</script>
		{% endfor %}
		<div class="container mb-5">
			<h1 class="text-center">Mon compte</h1>
			<div class="row mt-5">
				<div class="col-md-6">
					<div class="card">
						<div class="card-body d-flex flex-column text-center">
							<div class="icon">
								<div class="rounded-icon big-icon">
								<i class="fa fa-user"></i>
							</div>
							</div>
							<div class="info">
								<span class="text-gray">Adresse email</span>
							<h4>{{ app.user.email }}</h4>
							<hr>
							</div>
							<div class="info">
								<div class="row text-center">
								<div class="col-md-6">
									<span class="text-gray">Nom</span>
									<h4>{{ app.user.firstName }}</h4>
								</div>
								<div class="col-md-6">
									<span class="text-gray">Prénom</span>
									<h4>{{ app.user.lastName }}</h4>
								</div>
							</div>
							<hr>
							</div>
							<div class="info">
							{% if app.user.company %}
								<span class="text-gray">Société</span>
									<h4>{{ app.user.company }}</h4>
							{% endif %}
							</div>
							<div class="info">
								<a href="{{ path('editProfile') }}" class="button button-header">Modifier mon compte</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<h2>Mes évènements</h2>

					<div class="event-container">
						
							{% for event in events %}
							<div class="event-card row no-gutters">
							<div class="col-md-12">
									<div class="event-date h-100">
										<p class="event-day">{{ event.launchDate|date('d') }}<br/><span class="month">{{ event.launchDate|format_datetime(pattern='MMM') }}</span>
										</p>
									</div>
								</div>
								<div class="col-md-12">
									<div class="event-infos">
											<a href="{{ path('my_events_business',{'slug':event.slug}) }}" class="text-center text-md-left">
												<h1 class="event-title">{{ event.name }}</h1>
											</a>
											<div class="minimal-infos-container">
												<div class="rounded-icon primary-icon">
													<i class="fa fa-map-marker-alt"></i>
												</div>
												<span>{{ event.city }}
												-
												{{ event.launchDate|format_datetime(pattern='d MMMM yyyy') }}
												-
												{{ event.stopDate|format_datetime(pattern='d MMMM yyyy') }}</span>
											</div>
											<div class="ticket-container">
												<div class="rounded-icon primary-icon">
													<i class="fa fa-ticket-alt"></i>
												</div>
												<span>{{ event.price != 0 ? event.price ~" €" : "Gratuit" }}</span>
											</div>
											<div class="cashprize-container">
												<div class="rounded-icon primary-icon">
													<i class="fa fa-award"></i>
												</div>
												<span>
													{{ event.cashprize != 0 ? event.cashprize ~ " €" : "Aucun"}}</span>
											</div>

										</div>
								</div>
								</div>
							{% endfor %}
							<div class="d-flex justify-content-center align-items-center flex-column mt-1">
								<a href="{{ path('events_business_new') }}" class="button button-header w-100 text-center">Ajouter un évènement</a>
							<a href="{{ path('my_events') }}" class="button button-header w-100 mt-1 text-center">Voir tous mes évènements</a>
							</div>
						
					</div>
				</div>
			</div>

		</section>
	{% endblock %}